name: Test

on:
  - push
  - pull_request

jobs:

  yml-lint:
    runs-on: ubuntu-latest
    name: 'YML lint'
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - run: docker pull cytopia/yamllint
      - run: docker run --rm -t -v $(pwd):/data cytopia/yamllint --config-file=tests/.yamllint .

  markdown-lint:
    runs-on: ubuntu-latest
    name: 'Markdown lint'
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - run: docker pull tmknom/markdownlint
      - run: docker run --rm -v $(pwd):/work tmknom/markdownlint '**/*.md' --config tests/.markdownlintrc --ignore vendor --ignore CHANGELOG.md --ignore var --ignore tmp

  cs-lint:
    runs-on: ubuntu-latest
    name: 'CS Lint'
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2
      - run: composer install --dev --ignore-platform-req=php --quiet
        shell: bash
      - run: PHP_CS_FIXER_IGNORE_ENV=1 composer cs:list
        shell: bash

  psalm:
    runs-on: ubuntu-latest
    name: 'Psalm'
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2
      - run: composer install --ignore-platform-req=php --quiet
        shell: bash
      - run: composer psalm
        shell: bash

  phpstan:
    runs-on: ubuntu-latest
    name: 'Phpstan'
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2
      - run: composer install --ignore-platform-req=php --quiet
        shell: bash
      - run: composer phpstan
        shell: bash

  test-unit:
    runs-on: ubuntu-latest
    name: "Unit tests (PHP ${{ matrix.php-version }})"
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2', '8.3', '8.4']
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
      - run: composer install --ignore-platform-req=php --quiet
        shell: bash
      - run: composer test
        shell: bash
      - run: cat ./tests/test.log
        shell: bash

  test-unit-coverage:
    runs-on: ubuntu-latest
    name: "Running unit test coverage"
    env:
      XDEBUG_MODE: coverage
    timeout-minutes: 5
    needs:
      - test-unit
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: xdebug
          tools: composer:v2
      - run: composer install --ignore-platform-req=php --quiet
        shell: bash
      - run: composer test:coverage:xml
        shell: bash
      - uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: e0b199e87a2813189267e9baa3bf44d5354447ca73e8a4b2d8c027360b05523a
        with:
          coverageLocations: coverage.xml:clover
      - uses: actions/upload-artifact@v4
        with:
          name: coverage.xml
          path: coverage.xml

  test-mutant:
    runs-on: ubuntu-latest
    name: 'Mutant Test'
    timeout-minutes: 5
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2
      - run: composer install --ignore-platform-req=php --quiet
        shell: bash
      - run: composer test:mutant
        shell: bash
